AWSTemplateFormatVersion: '2010-09-09'
Description: Ejemplo de instancia EC2 con servidor Apache y Elastic IP

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Grupo de seguridad para acceso HTTP y HTTPS
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0  # Permite acceso desde cualquier dirección IP
        - IpProtocol: tcp
          FromPort: '443'
          ToPort: '443'
          CidrIp: 0.0.0.0/0  # Permite acceso desde cualquier dirección IP
  
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-01cd4de4363ab6ee8  # AMI de Amazon Linux 2
      KeyName: acastellanos_oregon
      UserData:
        Fn::Base64: |
          #!/bin/bash
          dnf update -y
          dnf install -y httpd.x86_64
          systemctl start httpd.service
          systemctl status httpd.service
          systemctl enable httpd.service
          echo "<!DOCTYPE html>" >> /var/www/html/index.html
          echo "<html>" >> /var/www/html/index.html
          echo "<head>" >> /var/www/html/index.html
          echo "<title>My Demo Web App</title>" >> /var/www/html/index.html
          echo "</head>" >> /var/www/html/index.html
          echo "<body bgcolor="black" text="teal">" >> /var/www/html/index.html
          echo "<center>" >> /var/www/html/index.html
          echo "<h1>Hola from My Demo Web App!</h1>" >> /var/www/html/index.html
          echo "<p>This is a simple static web page hosted on AWS.</p>" >> /var/www/html/index.html
          echo "</center>" >> /var/www/html/index.html
          echo "</body>" >> /var/www/html/index.html
          echo "</html>" >> /var/www/html/index.html
      
      SecurityGroupIds:
        - !Ref MySecurityGroup  # Asocia el grupo de seguridad a la instancia

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      InstanceId: !Ref MyEC2Instance

Outputs:
  InstanceId:
    Description: ID de la instancia EC2 creada
    Value: !Ref MyEC2Instance
  ElasticIP:
    Description: Elastic IP asociada a la instancia
    Value: !Ref MyEIP
